// Maps full country names to ISO 3166-1 alpha-2 country codes
export const countryNameToCode: Record<string, string> = {
  "United States": "US",
  "United Kingdom": "GB",
  "Canada": "CA",
  "Australia": "AU",
  "Germany": "DE",
  "France": "FR",
  "Spain": "ES",
  "Italy": "IT",
  "Netherlands": "NL",
  "Belgium": "BE",
  "Switzerland": "CH",
  "Austria": "AT",
  "Sweden": "SE",
  "Norway": "NO",
  "Denmark": "DK",
  "Finland": "FI",
  "Ireland": "IE",
  "Portugal": "PT",
  "Greece": "GR",
  "Poland": "PL",
  "Czech Republic": "CZ",
  "Hungary": "HU",
  "Romania": "RO",
  "Japan": "JP",
  "South Korea": "KR",
  "China": "CN",
  "India": "IN",
  "Singapore": "SG",
  "Malaysia": "MY",
  "Thailand": "TH",
  "Vietnam": "VN",
  "Indonesia": "ID",
  "Philippines": "PH",
  "New Zealand": "NZ",
  "Mexico": "MX",
  "Brazil": "BR",
  "Argentina": "AR",
  "Chile": "CL",
  "Colombia": "CO",
  "Peru": "PE",
  "South Africa": "ZA",
  "Egypt": "EG",
  "Nigeria": "NG",
  "Kenya": "KE",
  "UAE": "AE",
  "Saudi Arabia": "SA",
  "Israel": "IL",
  "Turkey": "TR",
  "Russia": "RU",
  "Ukraine": "UA",
};

// Helper to get country code from name, defaults to India
export function getCountryCode(countryName: string | null | undefined): string {
  if (!countryName) return "IN";
  return countryNameToCode[countryName] || "IN";
}
