/**
 * src/utils/signedUrl.ts — Firebase Storage signed URL layer
 *
 * Drop-in replacement for the Supabase signed URL utility.
 * Public API is identical so all callers compile without changes:
 *   getSignedUrl(bucket, path, expiresIn?)
 *   getSignedUrls(bucket, paths, expiresIn?)
 *   clearSignedUrlCache()
 *   invalidateSignedUrl(bucket, path)
 *   getDocumentImageUrl(imagePath)
 *   getTaskImageUrl(imagePath)
 *
 * Implementation notes
 * ─────────────────────
 * - Supabase used `bucket` + `path` separately. Firebase Storage uses a single
 *   full path.  The bucket parameter is kept in the API for backwards
 *   compatibility but is ignored — Firebase Storage uses the default bucket
 *   configured in client.ts.
 * - Time-limited URLs are generated by the getSignedUrl Cloud Function
 *   (server-side Admin SDK), matching Supabase's 1-hour signed URL TTL.
 * - In-memory + IndexedDB caching is preserved unchanged.
 * - Offline fallback to IndexedDB is preserved unchanged.
 */

import { callGetSignedUrl } from '@/integrations/firebase/functions';
import { cacheSignedUrl, getCachedSignedUrl } from './offlineStorage';

const DEFAULT_EXPIRY_SECONDS = 3600;
const REFRESH_BUFFER_MS      = 5 * 60 * 1000; // 5 minutes

/** In-memory cache: key = `${bucket}:${path}` */
const signedUrlCache = new Map<string, { url: string; expiresAt: number }>();

// ---------------------------------------------------------------------------
// Core
// ---------------------------------------------------------------------------

/**
 * Get a time-limited signed URL for a storage file.
 *
 * @param bucket    Kept for API compatibility — ignored (Firebase uses default bucket)
 * @param path      Full storage path, e.g. "documents/uid/docId/document.jpg"
 * @param expiresIn TTL in seconds (default 3600)
 */
export async function getSignedUrl(
  bucket: string,
  path: string,
  expiresIn: number = DEFAULT_EXPIRY_SECONDS,
): Promise<string | null> {
  if (!path) return null;

  const cacheKey = `${bucket}:${path}`;
  const cached   = signedUrlCache.get(cacheKey);
  const now      = Date.now();

  // Return in-memory cache if still fresh
  if (cached && cached.expiresAt > now + REFRESH_BUFFER_MS) {
    return cached.url;
  }

  // Offline: serve last-known URL from IndexedDB
  if (typeof navigator !== 'undefined' && !navigator.onLine) {
    const persisted = await getCachedSignedUrl(bucket, path).catch(() => null);
    if (persisted) return persisted;
  }

  try {
    const { signedUrl, expiresAt } = await callGetSignedUrl({
      storagePath:      path,
      expiresInSeconds: expiresIn,
    });

    // Cache in-memory
    signedUrlCache.set(cacheKey, {
      url:       signedUrl,
      expiresAt: new Date(expiresAt).getTime(),
    });

    // Persist for offline use (non-blocking)
    cacheSignedUrl(bucket, path, signedUrl, expiresIn).catch(() => {});

    return signedUrl;
  } catch (err) {
    console.error(`[signedUrl] Failed for ${path}:`, err);
    // Last resort: IndexedDB stale copy
    const persisted = await getCachedSignedUrl(bucket, path).catch(() => null);
    return persisted;
  }
}

/**
 * Get signed URLs for multiple paths in parallel.
 *
 * @param bucket    Kept for API compatibility
 * @param paths     Array of storage paths
 * @param expiresIn TTL in seconds
 */
export async function getSignedUrls(
  bucket: string,
  paths: string[],
  expiresIn: number = DEFAULT_EXPIRY_SECONDS,
): Promise<Map<string, string>> {
  const results: Map<string, string> = new Map();
  const toFetch: string[] = [];
  const now = Date.now();

  // Check in-memory cache first
  for (const path of paths) {
    if (!path) continue;
    const cacheKey = `${bucket}:${path}`;
    const cached   = signedUrlCache.get(cacheKey);
    if (cached && cached.expiresAt > now + REFRESH_BUFFER_MS) {
      results.set(path, cached.url);
    } else {
      toFetch.push(path);
    }
  }

  // Fetch uncached in parallel
  await Promise.all(
    toFetch.map(async (path) => {
      const url = await getSignedUrl(bucket, path, expiresIn);
      if (url) results.set(path, url);
    }),
  );

  return results;
}

// ---------------------------------------------------------------------------
// Cache management
// ---------------------------------------------------------------------------

export function clearSignedUrlCache(): void {
  signedUrlCache.clear();
}

export function invalidateSignedUrl(bucket: string, path: string): void {
  signedUrlCache.delete(`${bucket}:${path}`);
}

// ---------------------------------------------------------------------------
// Convenience wrappers (unchanged API)
// ---------------------------------------------------------------------------

export async function getDocumentImageUrl(imagePath: string | null): Promise<string | null> {
  if (!imagePath) return null;
  return getSignedUrl('document-images', imagePath);
}

export async function getTaskImageUrl(imagePath: string | null): Promise<string | null> {
  if (!imagePath) return null;
  return getSignedUrl('task-images', imagePath);
}
